#!/bin/bash
# GPLv2, Brian Mingus.
# build bibtex.js from texlive

#
# Step 0: Configuration
# You MUST do this first. Modifying anything else is optional.
#
workdir=$(pwd)
# obtain from http://mirrors.ctan.org/systems/texlive/Source
tldate=20120628 

#
# Step 1: Set up a clean workspace
#

mkdir -p $workdir
cd $workdir
tldir=texlive-${tldate}-source
tlfile=${tldir}.tar.xz
rm -fr $tldir src build

if [[ ! -f $tlfile ]]; then
    wget "http://mirrors.ctan.org/systems/texlive/Source/$tlfile"
fi

tar -xf $tlfile
mv $tldir src
mkdir build

#
# Step 2: configure and make regular executables
# These are borrowed from the build script in texlive.js
#

OPTS="--without-x --disable-shared"

mkdir -p build/texk/kpathsea build/texk/web2c

cd build/texk/kpathsea
sed -ri 's/assert\ \(ret\)/\/\/assert\ \(ret\)/' ../../../src/texk/kpathsea/progname.c
../../../src/texk/kpathsea/configure $OPTS
make

cd ../web2c
../../../src/texk/web2c/configure $OPTS
make bibtex

function backupbins {
    cp tangleboot tangleboot.bck
    cp tangle tangle.bck
    cp web2c/web2c web2c/web2c.bck
    cp web2c/fixwrites web2c/fixwrites.bck
    cp web2c/splitup web2c/splitup.bck
}

function restorebins {
    cp tangleboot.bck tangleboot
    cp tangle.bck tangle
    cp web2c/web2c.bck web2c/web2c
    cp web2c/fixwrites.bck web2c/fixwrites
    cp web2c/splitup.bck web2c/splitup
    chmod +x tangleboot tangle web2c/web2c web2c/fixwrites web2c/splitup
}

backupbins

cd ../kpathsea
emconfigure ../../../src/texk/kpathsea/configure $OPTS
#sed -ri 's/\".*\"$/\"\/\"/' paths.h
emmake make

cd ../web2c
make clean
restorebins
emconfigure ../../../src/texk/web2c/configure $OPTS
emmake make bibtex

restorebins
emmake make bibtex

cp tangleboot.bck tangleboot
chmod +x tangleboot
emmake make bibtex

cp tangle.bck tangle
chmod +x tangle
emmake make bibtex


#OPTS="-O0"                                                            # .703s
#OPTS="-O1"                                                            # .943s
#OPTS="-O1 --closure 1"                                                # .927s
#OPTS="-O0 --closure 1"                                                # .650s better
#OPTS="-O0 --llvm-opts 3 --closure 1"                                  # .946s
#OPTS="-O0 --llvm-opts 2 --closure 1"                                  # .950s
#OPTS="-O0 --llvm-opts 1 --closure 1"                                  # .946s
#OPTS="-O2"                                                            # breaks
#OPTS="-O0 --closure 1 -s INLINING_LIMIT=0"                            # 1.7s
#OPTS="-O0 --closure 1 -s DOUBLE_MODE=0"                               # .648s
#OPTS="-O0 --closure 1 -s PRECISE_I64_MATH=0"                          # .663s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=0"                          # 1.8s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=1"                          # 1.8s
#OPTS="-O0 --closure 1 -s QUANTUM_SIZE=1 -s USE_TYPED_ARRAYS=0"        # breaks
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2"                           # .557s better
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1"               # .335s better
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1 -s ASSERTIONS=0"  # .335s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1 -s DISABLE_EXCEPTION_CATCHING=1" # .333s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1 -s INLINING_LIMIT=0"               # 1.6s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1 -s DOUBLE_MODE=0"               # .346s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1 -s CORRECT_SIGNS=0 -s CORRECT_OVERFLOWS=0 -s CORRECT_ROUNDINGS=0 -s DOUBLE_MODE=0 -s PRECISE_I64_MATH=0"  # .319s
#OPTS="-O0 --closure 1 -s USE_TYPED_ARRAYS=2 -s RELOOP=1"  # .333s breaks as webworker
OPTS="-O0  -s USE_TYPED_ARRAYS=2 -s RELOOP=1"  # .836s :(


cp -r ../../../demo_files/{test.aux,plain.bst,refs.bib,ls-R,texmf.cnf,texmf-config,texmf-var,texmf,texmf-local,texmf-dist,bin} .
cp ../../../release/pre.js ../../../release/post.js .

env EMCC_DEBUG=1 emcc $OPTS -o bibtex.sa.js bibtex.o  lib/lib.a ../kpathsea/.libs/libkpathsea.a --embed-file test.aux --embed-file plain.bst --embed-file refs.bib --embed-file bin --embed-file texmf.cnf
time node bibtex.sa.js test

env EMCC_DEBUG=1 emcc $OPTS -o bibtex.js bibtex.o  lib/lib.a ../kpathsea/.libs/libkpathsea.a --pre-js pre.js --post-js post.js --embed-file texmf.cnf --embed-file bin
cp bibtex.js ../../../release/bibtex-webworker.js
